name: Docker - Deploy

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      service:
        type: string
        required: true
      service_path:
        type: string
        default: '.'
        required: true
      namespace:
        type: string
        required: true
    secrets:
      AWS_ACCESS_KEY_DEVELOPMENT:
        required: true
      AWS_SECRET_ACCESS_KEY_DEVELOPMENT:
        required: true      

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: enabled

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Configure ECR AWS credentials (dev)
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_DEVELOPMENT }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEVELOPMENT }}
          aws-region: ca-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1 

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ inputs.service }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ inputs.service }}-buildx-
      
      - name: Generate env vars
        run: |
          echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
          echo "GIT_REF=`echo ${GITHUB_REF##*/}`" >> $GITHUB_ENV
      
      - name: Build and push
        id: docker_build
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ inputs.namespace }}/${{ inputs.service }}
        uses: docker/build-push-action@v2
        with:
          context: ./${{ inputs.service_path }}
          file: ./${{ inputs.service_path }}/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.GIT_REF }}-${{ env.SHORT_SHA }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Kubernetes resource setup
        env:
          ECR_IMAGE: ${{ steps.login-ecr.outputs.registry }}/${{ inputs.namespace }}/${{ inputs.service }}:${{ env.GIT_REF }}-${{ env.SHORT_SHA }}
        run: |
          cd ${{ inputs.service_path }}/infrastructure/kubernetes/${{ inputs.environment }}
          sed -i "s|image:.*|image: $ECR_IMAGE|" ${{ inputs.service }}.yaml
          
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Bump image tag (run number: ${GITHUB_RUN_NUMBER})"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}