name: JavaScript - PR

on:
  workflow_call:
    inputs:
      working_directory:
        type: string
        default: '.'
        required: false

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: |
          cd ${{ inputs.working_directory }}
          echo "::set-output name=dir::$(yarn cache dir)"
      
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        working-directory: ${{ inputs.working_directory }}
        shell: bash
        run: |
          yarn install
         
      - name: Build
        working-directory: ${{ inputs.working_directory }}
        shell: bash
        run: |
          yarn build